name: Apply DB migrations

on:
  push:
    branches: [ main ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install psql client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Apply migrations
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          set -e
          if [ -z "$DATABASE_URL" ]; then
            echo "SUPABASE_DB_URL is not set, skipping migrations"
            exit 1
          fi
          for f in log-sticaLCDM-app/migrations/*.sql; do
            echo "Applying $f"
            psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
          done
